name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04-ppc64le
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          architecture: ppc64le
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: |
          echo ::add-matcher::.github/eslint.json
          yarn run eslint src test --format=compact
      - run: yarn test
      - run: yarn prepublishOnly
      - run: yarn docs:build
